[book]
authors = ["Luuk van Houten"]
description = "A game called Space Invaders, loosely based on the original."
language = "en"
multilingual = false
src = "docs"
title = "Space Invaders"

[build]
build-dir = "target/docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/luuk-vanhouten/Space-Invaders-OOPD-Project"
